"""
image_engine.py
Media Engine & Image Specialist module for SE226 Album Cover Studio.

Responsibilities:
- Combine Gemini cover prompt with genre visual style
- Generate album cover image using Pollinations.ai
- Download and return the image as a PIL.Image object
"""

from __future__ import annotations

import io
from urllib.parse import quote

import requests
from PIL import Image


POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt"


GENRE_VISUAL_STYLES = {
    "Pop": "vibrant colors, clean modern pop album cover, glossy lighting",
    "Rock": "dramatic lighting, gritty texture, bold rock album cover style",
    "Hip-Hop / Rap": "urban street aesthetic, high contrast, cinematic hip-hop cover",
    "Electronic": "neon lights, futuristic digital art, synthwave atmosphere",
    "Indie": "soft film photography, minimal indie aesthetic, dreamy composition",
    "R&B / Soul": "warm lighting, elegant soulful mood, smooth cinematic cover",
    "Jazz": "vintage jazz club atmosphere, warm tones, classic album design",
    "Metal": "dark grainy atmosphere, intense contrast, heavy metal cover art",
    "Türk Pop": "colorful Turkish pop aesthetic, energetic and modern cover",
    "Klasik": "elegant classical music cover, refined composition, soft lighting",
}


def build_final_cover_prompt(cover_prompt: str, genre: str) -> str:
    """
    Combines Gemini's cover prompt with a genre-based visual style.

    Args:
        cover_prompt: Prompt generated by Gemini.
        genre: Selected genre from the GUI.

    Returns:
        Final prompt string for image generation.
    """
    base_prompt = cover_prompt.strip() if cover_prompt else "fictional music album cover"
    genre_style = GENRE_VISUAL_STYLES.get(
        genre,
        "professional album cover art, high quality, detailed, square composition"
    )

    final_prompt = (
        f"{base_prompt}. "
        f"Visual style: {genre_style}. "
        "No text, no logo, no watermark, square album cover, high quality."
    )
    return final_prompt


def generate_cover_image(
    cover_prompt: str,
    genre: str,
    width: int = 600,
    height: int = 600,
    timeout: int = 90,
) -> Image.Image:
    """
    Generates an album cover image using Pollinations.ai.

    Args:
        cover_prompt: Cover prompt generated by Gemini.
        genre: Selected music genre.
        width: Image width.
        height: Image height.
        timeout: Request timeout in seconds.

    Returns:
        PIL.Image.Image object in RGB mode.

    Raises:
        requests.RequestException: If the image request fails.
        PIL.UnidentifiedImageError: If returned content is not a valid image.
    """
    final_prompt = build_final_cover_prompt(cover_prompt, genre)
    encoded_prompt = quote(final_prompt)

    url = (
        f"{POLLINATIONS_BASE_URL}/{encoded_prompt}"
        f"?width={width}&height={height}&nologo=true"
    )

    response = requests.get(url, timeout=timeout)
    response.raise_for_status()

    image = Image.open(io.BytesIO(response.content)).convert("RGB")
    return image
